security:
    consumer_key:       {consumerKey}
    consumer_secret:    {consumerSecret}

details:
    learnosity_env:     https://data.learnosity.com/v1
    endpoint:           /{some learnosity endpoint}
